import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full overflow-hidden bg-primary">
        <div className="sm:px-16 px-6 w-full flex justify-start items-center">
          <div className="xl:max-w-[1280px] w-full">
            <Navbar />
          </div>
        </div>

        <div className="bg-primary flex justify-center items-start">
          <div className="xl:max-w-[1280px] w-full">
            <Sidebar />
          </div>
        </div>
      </div>
    </>
  );
}
